apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: core-services
data:
  NODE_ENV: "development"
  PORT: "3001"
  SERVICE_NAME: "fleet-os-auth-service"
  LOG_LEVEL: "debug"
  CLIENT_URL: "http://localhost:3000"
  ACCESS_TOKEN_EXP: "15m"
  REFRESH_TOKEN_EXP: "7d"
