apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-config
  namespace: core-services
data:
  NODE_ENV: "development"
  PORT: "3004"
  SERVICE_NAME: "fleet-os-fleet-service"
  LOG_LEVEL: "debug"
  AUTH_SERVICE_URL: "http://auth-service.core-services.svc.cluster.local:3001"
  AUTH_SERVICE_API_KEY: "dev-internal-key"