apiVersion: v1
kind: Secret
metadata:
  name: inventory-secret
  namespace: core-services
type: Opaque
data:
  # mongodb://admin:cantremember@mongo-db.infrastructure:27017/inventory-db?authSource=admin
  DATABASE_URL: "bW9uZ29kYjovL2FkbWluOmNhbnRyZW1lbWJlckBtb25nby1kYi5pbmZyYXN0cnVjdHVyZToyNzAxNy9pbnZlbnRvcnktZGI/YXV0aFNvdXJjZT1hZG1pbg=="
  # redis://redis-stack.infrastructure:6379
  REDIS_URL: "cmVkaXM6Ly9yZWRpcy1zdGFjay5pbmZyYXN0cnVjdHVyZTo2Mzc5"
