apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
  namespace: core-services
data:
  NODE_ENV: "development"
  PORT: "3003"
  SERVICE_NAME: "fleet-os-inventory-service"
  LOG_LEVEL: "debug"
