apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: core-services
data:
  NODE_ENV: "development"
  PORT: "3005"
  SERVICE_NAME: "fleetos-notification-service"
  LOG_LEVEL: "debug"
  # Kafka Configuration
  KAFKA_BROKER: "kafka.infrastructure.svc.cluster.local:9092"
  KAFKA_GROUP_ID: "notification-service-group"
  # Email Configuration (Gmail)
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  EMAIL_FROM: "fleetos.logistics@gmail.com"
