apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: core-services
type: Opaque
data:
  # mongodb://admin:cantremember@mongo-db.infrastructure:27017/notification-db?authSource=admin
  DATABASE_URL: "bW9uZ29kYjovL2FkbWluOmNhbnRyZW1lbWJlckBtb25nby1kYi5pbmZyYXN0cnVjdHVyZToyNzAxNy9ub3RpZmljYXRpb24tZGI/YXV0aFNvdXJjZT1hZG1pbg=="
  
  SMTP_USER: "ZmxlZXRvcy5sb2dpc3RpY3NAZ21haWwuY29t" 
  SMTP_PASSWORD: "amVyaWdjZHFuZXJ4dHJ2eA==" 
