apiVersion: v1
kind: ConfigMap
metadata:
  name: shipment-config
  namespace: core-services
data:
  NODE_ENV: "development"
  PORT: "3002"
  SERVICE_NAME: "fleet-os-shipment-service"
  LOG_LEVEL: "debug"
