services:
  mongo-db:
    container_name: mongo-db
    image: mongo:7.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: cantremember
    volumes:
      - mongodb-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  redis-stack:
    container_name: redis-stack
    image: redis/redis-stack:7.2.0-v18
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  auth-service:
    container_name: fleetOS-auth-service
    image: fleet-os-auth-service-image
    build:
      context: ./fleet-os-auth-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./fleet-os-auth-service:/app
      - /app/node_modules
    ports:
      - 3001:3001
    depends_on:
      - mongo-db
    env_file:
      - ./fleet-os-auth-service/.env
    networks:
      - app-network

  shipment-service:
    container_name: fleetOS-shipment-service
    image: fleet-os-shipment-service-image
    build:
      context: ./fleet-os-shipment-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./fleet-os-shipment-service:/app
      - /app/node_modules
    ports:
      - 3002:3002
    depends_on:
      - mongo-db
      - redis-stack
    env_file:
      - ./fleet-os-shipment-service/.env
    networks:
      - app-network

  inventory-service:
    container_name: fleetOS-inventory-service
    image: fleet-os-inventory-service-image
    build:
      context: ./fleet-os-inventory-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./fleet-os-inventory-service:/app
      - /app/node_modules
    ports:
      - 3003:3003
    depends_on:
      - mongo-db
      - redis-stack
    env_file:
      - ./fleet-os-inventory-service/.env
    networks:
      - app-network

  fleet-service:
    container_name: fleetOS-fleet-service
    image: fleet-os-fleet-service-image
    build:
      context: ./fleet-os-fleet-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./fleet-os-fleet-service:/app
      - /app/node_modules
    ports:
      - 3004:3004
    depends_on:
      - mongo-db
      - redis-stack
    env_file:
      - ./fleet-os-fleet-service/.env
    networks:
      - app-network

  kong:
    container_name: kong
    image: kong:3.9
    restart: always
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml
    ports:
      - "8000:8000"
      - "8002:8001"
      - "8443:8443"
      - "8444:8444"
    networks:
      - app-network

volumes:
  mongodb-data:
  redis-data:

networks:
  app-network:
    driver: bridge
